// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {application} from '../models';

export function AddSkill(arg1:string,arg2:string):Promise<void>;

export function DeleteAllSkills():Promise<void>;

export function DeleteSkill(arg1:string):Promise<Array<application.Skill>>;

export function GetConstants():Promise<application.MessagesStruct>;

export function GetSkills():Promise<Array<application.Skill>>;
