// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSkill(arg1) {
  return window['go']['main']['App']['AddSkill'](arg1);
}

export function DeleteAllSkills() {
  return window['go']['main']['App']['DeleteAllSkills']();
}

export function DeleteSkill(arg1) {
  return window['go']['main']['App']['DeleteSkill'](arg1);
}

export function GetConstants() {
  return window['go']['main']['App']['GetConstants']();
}

export function GetSkills() {
  return window['go']['main']['App']['GetSkills']();
}
