// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddSkill(arg1:string,arg2:string):Promise<void>;

export function DeleteAllSkills():Promise<void>;

export function DeleteSkill(arg1:string):Promise<Array<main.Skill>>;

export function GetConstants():Promise<main.MessagesStruct>;

export function GetSkills():Promise<Array<main.Skill>>;
